import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next on every build and carries a
    // "should not be edited" banner, so its triple-slash references are not
    // ours to fix. graft/ and admin/ are vendored, not authored here.
    ignores: [
      ".next/**",
      ".open-next/**",
      ".wrangler/**",
      "node_modules/**",
      "public/admin/**",
      "next-env.d.ts",
      "graft/**",
    ],
  },
  {
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "CallExpression[callee.name='fetch'] > Literal[value=/english-learning-backend/]",
          message: "Do not fetch Render from outside lib/server/backend.ts",
        },
      ],
    },
  },
];

export default config;
